config/routes.rb
Rails.application.routes.draw do
  
  resources :shots do

    resources :comments
    #shot/1/comment/3
      member do 
        put 'like', to: "shots#like"
        put 'unlike', to: "shots#unlike"
      end
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  root "shots#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :shot
    belongs_to :user
end

app/models/shot.rb
class Shot < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    mount_uploader :user_shot, UserShotUploader

    is_impressionable
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
  has_many :shots, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @shot = Shot.find(params[:shot_id]) # finds the shot with the associated shot_id
    @comment = @shot.comments.create(comment_params) # creates the comment on the shot passing in params
    @comment.user_id = current_user.id if current_user # assigns logged in user's ID to comment
    @comment.save!

    redirect_to shot_path(@shot)
  end


  def destroy
    @shot = Shot.find(params[:shot_id])
    @comment = @shot.comments.find(params[:id])
    @comment.destroy
    redirect_to shot_path(@shot)
  end

  private


  def comment_params 
    params.require(:comment).permit(:name, :response)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


private


def sign_up_params

    params.require(:user).permit(:name, :email, :password, :password_confirmation)

end 

def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
end
    

end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]
  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all.order('created_at DESC')
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = current_user.shots.build(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to shots_url, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @shot.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @shot.unliked_by current_user
    respond_to do |format|

    format.html { redirect_back fallback_location: root_path }
    format.json { render layout:false }
  end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_shot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def verbose_date(date)
        date.strftime('%B %d %Y')
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.email.gsub('spam', 'mdeering'), alt: comment.user.name, gravatar: { size: 48 }) %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong>
          <div><%= comment.response %></div>
        </p>
      </div>
    </div>
    <% if (user_signed_in? && (current_user.id == comment.user_id)) %>
       <%= link_to 'Delete', [comment.shot, comment],
                  method: :delete, class: "btn btn-dark", data: { confirm: 'Are you sure you want to delete this comment?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@shot, @shot.comments.build]) do |f| %>
  <div class="field">
        <div class="control">
            <%= f.input :name, input_html: { class: 'form-control'}, wrapper: false, label_html: { class: 'label' } %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :response, input_html: { class: 'form-control' }, wrapper: false, label_html: { class: 'label' } %>
        </div>
    </div>

    <br>
    <br>
    
    <%= f.button :submit, 'Leave a reply', class: 'btn btn-primary rose' %>



<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbleclone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      
      <%= link_to 'Dribble Clone', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          
        </ul>
        <ul class="navbar-nav mr-auto">
          <% if current_user %>
          <li class="nab-item"> <span><%= link_to "Sign Out",
            destroy_user_session_path, class: 'nav-link', method: :delete %></span>

             </li>
          

         <li class="nav-item">
                <%= link_to new_shot_path, class: 'btn btn-primary rose'  do %>
                  <span class="icon is-small"><i class="fa fa-upload"></i></span>
                  <span>New Shot</span>
                <% end %>
              </li>

              <li class="nav-item"><span>
                <%= link_to current_user.name, edit_user_registration_path, class: 'nav-link' %>
              </span>
            </li>

          <% else %>

          <li class="nav-item"><span><%= link_to "Sign Up", 
           new_user_registration_path, class: 'nav-link' %></span></li>
          <li class="nav-item"><span><%= link_to "Sign In", new_user_session_path, 

          class: 'nav-link' %></span></li>
          </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/shots/_form.html.erb
<%= simple_form_for @shot, html: { multipart: true }  do |f| %>
  <%= f.error_notification %>
  <div class="columns is-centered">
    <div class="column is-half">
    
    <% unless @shot.user_shot.blank? %>
    <%= image_tag (@shot.user_shot_url), id: "previewImage" %>
    <% end %>

    <output id="list"></output>
    <div id="drop_zone">Drag your shot here</div>
    <br />

    <div class="hidden">
    <%= f.input :user_shot, label: false, input_html: { class: "file-input", type: "file" }, wrapper: false, label_html: { class: "file-label" } %>
  </div>

  
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :description, input_html: { class: "form-control"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <br>
    <br>

    <div class="field">
      <div class="control">
        <%= f.button :submit, class:"btn btn-primary rose" %>
      </div>
    </div>
  </div>
</div>

 
<% end %>

app/views/shots/_hero.html.erb
 <% if !user_signed_in? %>
<section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">What are you working on?</h1>
          <p class="lead text-muted">Dribbble is where designers get inspired and hired.</p>
          <p>
            
          </p>
        </div>

        <div class="container">
           <%= link_to "Login", new_user_session_path, class: "btn btn-dark" %>
        </div>
        
</section>
<% end %>

app/views/shots/edit.html.erb
<section class="section">


<div class="container">
<h1>Editing Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

</div>
</section>

app/views/shots/index.html.erb
<main role="main">

      <%= render 'hero' %>


      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <% @shots.each do |shot| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                
               <%= link_to shot, class:"shot" do %>

                <%= image_tag(shot.user_shot_url, class: "card-img-top") %>
               

               <% end %>
                <div class="card-body">
                  <p class="card-text"><%= shot.title %></p>
                  <p class="card-text"><%= truncate(shot.description, length: 60)  %></p>
                  <p class="card-text"><%= time_ago_in_words(shot.created_at) %></p>
                  <div class="d-flex justify-content-between align-items-center">
                   

                   <div class="level-item views">
                    <%= link_to shot do %>
                  <span class="icon data"><i class="fa fa-eye"></i></span>
                  <%= shot.impressionist_count %>
                <% end %>
              </div>

                <div class="level-item comments data">

                <%= link_to shot do %>
                  <span class="icon data"><i class="fa fa-comment"></i></span>
                  <%= shot.comments.count %>
                <% end %>

              </div>


                <div class="level-item likes">
        
        <% if user_signed_in? %> 
        <% if  current_user.liked? shot %>
        <%= link_to unlike_shot_path(shot), method: :put, class: "unlike_shot" do %>
          <span class="icon"><i class="fa fa-heart has-text-primary" aria-hidden="true"></i></span>
          <span class="vote_count"><%= shot.get_likes.size %></span>
         <% end %>
      <% else %>
     
      <%= link_to like_shot_path(shot), method: :put, class: "like_shot" do %>
          <span class="icon"><i class="fa fa-heart" aria-hidden="true"></i></span>
          <span class="vote_count"><%= shot.get_likes.size %></span>

         <% end %>

      <% end %>

      <% else %>

      <%= link_to like_shot_path(shot), method: :put, class: "like_shot" do %>
          <span class="icon"><i class="fa fa-heart" aria-hidden="true"></i></span>
          <span class="vote_count"><%= shot.get_likes.size %></span>
         <% end %>
        <% end %>
      

      </div>


                  <td></td

                </div>
              </div>
            </div>

        <div class="user-data">
          <div class="user-thumb">
            <%= gravatar_image_tag(shot.user.email.gsub('spam', 'mdeering'), alt: shot.user.name, gravatar: { size: 20 }) %>
          </div>
           <div class="user-name"><%= shot.user.name %></div>
        </div>
        </div>
        </div>
            <% end %>
            

            
          
        
      </div>
      </div>
       </div>
    </main>

app/views/shots/new.html.erb
<section class="section">


<h1>What are you working on?</h1>

<div class="container">
<%= render 'form', shot: @shot %>

<%= link_to 'Back', shots_path %>

</div>

</section>

app/views/shots/show.html.erb
<div class="container">

<hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <br>
            <br>
            <br>

  <!-- STRIPED TABLE -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"></th>
                    <td><div class="column is-3 is-offset-1">
        <div class="nav panel show-shot-analytics">
         <div class="panel-block views data">
             
             <span class="icon"><i class="fa fa-eye" aria-hidden="true"></i></span>
             <%= pluralize(@shot.impressionist_count, 'View') %>
             
         </div>
         <div class="panel-block comments data">
            <span class="icon"><i class="fa fa-comment" aria-hidden="true"></i></span>

          <%= pluralize(@shot.comments.count, 'Comment') %>
         </div>
         <div class="panel-block likes data">
            <% if user_signed_in? %> 
        <% if  current_user.liked? @shot %>
        <%= link_to unlike_shot_path(@shot), method: :put, class: "unlike_shot" do %>
          <span class="icon"><i class="fa fa-heart has-text-primary" aria-hidden="true"></i></span>
          <span class="vote_count"><%= pluralize(@shot.get_likes.size, 'Like') %></span>
         <% end %>
      <% else %>
     
      <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
          <span class="icon"><i class="fa fa-heart" aria-hidden="true"></i></span>
           <span class="vote_count"><%= pluralize(@shot.get_likes.size, 'Like') %></span>

         <% end %>

      <% end %>

      <% else %>

      <%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
          <span class="icon"><i class="fa fa-heart" aria-hidden="true"></i></span>
          <span class="vote_count"><%= @shot.get_likes.size %></span>
         <% end %>
        <% end %>
         </div>
        </div>

 </div></td>
                    <td></td>
                    <td></td>
                </tr>
                
            </tbody>
        </table>
          </div>
          <div class="col-md-5 order-md-1">

            <h1 class="title is-3"><%= @shot.title %></h1>
   <div class="columns">
     <div class="column is-8">
       <span class="by has-text-grey-light">by</span>
         <div class="user-thumb">
          <%= gravatar_image_tag(@shot.user.email.gsub('spam', 'mdeering'), alt: @shot.user.name, gravatar: { size: 20 }); %>

         </div>
         <div class="user-name has-text-weight-bold"><%= @shot.user.name %></div>

         <div class="shot-time"><span class="has-text-grey-light">posted</span><span class="has-text-weight-semibold">
        <%= verbose_date(@shot.created_at) %>

         </span></div>
     </div>

   </div>
        
        <div class="shot-container">
           <div class="shot-full">
            <%= image_tag @shot.user_shot_url, class: 'featurette-image img-fluid mx-auto' unless @shot.user.blank? %>

          </div>

           <% if user_signed_in? && (current_user.id == @shot.user_id) %>
          <div class="buttons has-addons">
            <%= link_to 'Edit', edit_shot_path(@shot), class: "btn btn-primary" %>
            <%= link_to 'Delete', shot_path, class: "btn btn-dark", method: :delete, data: { confirm: 'Are you sure you want to delete this shot?'} %>
          </div>
       <% end %>
       <%= @shot.description %>
       </div> 

       <section class="comments">
        <h2 class="subtitle is-5"><%= pluralize(@shot.comments.count, 'Comment') %></h2>


         <%= render @shot.comments %>
      <hr />
      <% if user_signed_in? %>
       <div class="comment-form">
        <h3 class="subtitle is-3">Leave a reply</h3>
         <%= render 'comments/form' %>
       </div>


      <% else %>

      <div class="content"><%= link_to 'Sign in', new_user_session_path, class: 'btn btn-dark' %></div>
      <% end %>


        </div>










          </div>


        </div>

        </div>